#!/bin/bash

source /usr/share/debconf/confmodule

db_input high himbeerserver/github_client_id
db_go

db_input high himbeerserver/github_client_secret
db_go

db_input high himbeerserver/discord_client_id
db_go

db_input high himbeerserver/discord_client_secret
db_go
