#!/bin/bash

echo -en " [i] Replacing 000-default.conf ...\r"

rm /etc/apache2/sites-available/000-default.conf
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

ln -s /etc/himbeerserver/000-default.conf /etc/apache2/sites-available/000-default.conf
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

echo -e " [\e[32m✓\e[0m] Replaced 000-default.conf     "

a2enmod cgi
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

echo -en " [i] Restarting apache2 ...\r"

service apache2 restart
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

echo -e " [\e[32m✓\e[0m] Restarted apache2     "

luarocks install http
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

luarocks install lunajson
if [ $? != 0 ]; then
	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
	exit 1
fi

echo -e " [\e[32m✓\e[0m] Successfully installed himbeerserver"
