#!/bin/bash

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
	source /usr/share/debconf/confmodule
	db_purge
	db_fset himbeerserver/domain seen false
	db_fset himbeerserver/email seen false
fi
